import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css"

//componentes
import Header from "@/components/layout/header";
import Main from "@/components/layout/main";
import Footer from "@/components/layout/footer";

const poppins = Poppins({
    subsets: ["latin"],
    weight: [
      "100","200","300","400","500","600","700","800","900"
    ]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={poppins.className}>
          <Header/>
          <Main>
            <p>oi</p>
          </Main>
          <Footer></Footer>
        {children}
      </body>
    </html>
  );
}
